name: CD

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} #K-atarinaVujovic/intens-api-2022

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # can read repo code
      packages: write # can push to ghcr
      id-token: write # can use identity token to sign image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/sigstore/cosign-installer
      - name: Install cosign # install the signing tool
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Logging into ghcr to be able to push the image
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Prepare tags and labels for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta # id for later reference
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} # ghcr.io/k-atarinavujovic/intens-api-2022 (metadata action automatically lowercases)

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: . 
          push: true
          tags: ${{ steps.meta.outputs.tags }} # ghcr.io/k-atarinavujovic/intens-api-2022:latest
          labels: ${{ steps.meta.outputs.labels }} # additional info
          cache-from: type=gha # read cache from Github Actions cache
          cache-to: type=gha,mode=max # write to Github Actions cache. mode=max means cache intermediate layers too

      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image # sign image for security reasons
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }} # hashed image contents
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

  # https://blog.railway.com/p/github-actions
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      IMAGE_REF: ghcr.io/${{ github.repository }}:${{ github.ref_name }} # ghcr.io/K-atarinaVujovic/intens-api-2022:master
      SVC_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Lowercase image ref
        run: echo "IMAGE_REF=$(echo ${{ env.IMAGE_REF }}) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV 
      - name: Install cosign # install the signing tool
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'
      - name:  Verify signature
        run: |
          cosign verify ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            --certificate-identity ${{ github.server_url }}/${{ github.workflow_ref }} \
            --certificate-oidc-issuer https://token.actions.githubusercontent.com
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      - name: Deploy to railway
        run: railway redeploy --service=${{ env.SVC_ID }} -y
      
